### ISSUE TITLE
Quel est le sujet de maths de demain monsieur FlashOnFire?

### ISSUE THREAD

**Issue by Claquettes** [FlashOnFire/Cours#1]
@FlashOnFire

**Comment by FlashOnFire** [comment]
Mimir moment + feur

**Comment by Claquettes** [comment]
LIFAP2 + Polymanu + ratio + Google ChromeCast

**Comment by FlashOnFire** [comment]
Take the L + rip bozo + auttgames + Simon Masnou + développement limité + ucbl portail + pdt + metro C + Eddy Malou

**Comment by Claquettes** [comment]
Chaise pliante + inégalité de Cauchy Schwartz + no polypoints + eduroam + grapic + le duke + macdo charpennes

**Comment by FlashOnFire** [comment]
Chocolat Viennois + raclette + Intégrale de Riemann + Macbook Air + de a u 4 + hubble telescope + sigma grindset + distributivité simple + LIFRW

**Comment by Claquettes** [comment]
Chargeur usb C + métro c + inflation + Pablo + pyjama dinausore + Jonnhy Halliday à Bercy + + QWERTY + télésiège + fraude fiscale + escalope milanaise + les lacs du côneMara

**Comment by FlashOnFire** [comment]
Rubik's cube + leo in the baignoire + François Lê + Le pivot de Gauss + L'aventurier + matrice échelonnée + mocap + l'abonnement velov à 16€ + gdb + module image + la belote + Level'Up + mister mv + stabilo boss + sauce algérienne + ligma + pikachu

**Comment by Claquettes** [comment]
Scwheps agrume + legrand electronique + BDW TP5 + elodie + valise + méthode d'orthonormalisation de gram-schmidt + hannah montana + les simsons le film + actifry + pic pic alcool et drame + bourre bourre jfais un dram + OM-PSG + 30 mg de sucre en poudre + nescafé + chignon

**Comment by Claquettes** [comment]
Comme une envie de faire un script en python qui les génères tout seul mdr
@FlashOnFire

**Comment by FlashOnFire** [comment]
France-Dijon + Oignon rouge + Méthode Roux + coefficient de raideur + le rap français + la myopie + acide hyaluronique + eau pétillante + chicken louisiane steackhouse + france tv + Rust + plaque tectonique

**Comment by Claquettes** [comment]
https://github.com/Claquettes/ratio-generateur
